# ============================================================
# PaySentinelIQ — Robust Multi-Method PDF Text Extraction
# ============================================================
# CRITICAL: PDFs generated with canvas APIs (ReportLab, iText,
# FPDF, etc.) frequently produce garbled/empty text when using
# pdfplumber or pypdf alone. This module tries PyMuPDF first
# (best for canvas PDFs), then pdfplumber, then pypdf as fallback.
# Returns the most complete result.
# ============================================================

from __future__ import annotations

import io
import logging
from typing import Any

logger = logging.getLogger(__name__)


def extract_pdf_text_robust(pdf_bytes: bytes) -> str:
    """Try to extract text using multiple methods in quality order.
    
    Returns the most complete result (longest text). If all methods
    fail, raises ValueError.

    Method priority:
        1. PyMuPDF (fitz) — best for canvas/ReportLab PDFs
        2. pdfplumber — best for PDFs with table structures
        3. pypdf — fallback

    Args:
        pdf_bytes: Raw PDF file bytes.

    Returns:
        Extracted text string.

    Raises:
        ValueError: If no method could extract text.
    """
    results: list[tuple[str, str]] = []

    # ── Method 1: PyMuPDF (fitz) ──
    # Best for PDFs generated by ReportLab, iText, FPDF, and other
    # canvas-based generators where text objects are embedded but
    # may be out-of-order in the content stream.
    try:
        import fitz  # PyMuPDF

        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        text_fitz = ""
        for page in doc:
            # get_text("dict") preserves blocks and positions —
            # more faithful to layout than plain get_text()
            blocks = page.get_text("dict")["blocks"]
            for block in blocks:
                if block.get("type") == 0:  # type 0 = text block
                    for line in block.get("lines", []):
                        for span in line.get("spans", []):
                            text_fitz += span["text"] + " "
                        text_fitz += "\n"
        doc.close()
        results.append(("pymupdf", text_fitz.strip()))
        logger.debug("PyMuPDF extraction: %d chars", len(text_fitz.strip()))
    except Exception as e:
        logger.warning("PyMuPDF (fitz) extraction failed: %s", e)

    # ── Method 2: pdfplumber ──
    # Good for PDFs with table structures and conventional layouts.
    try:
        import pdfplumber

        with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
            text_plumber = ""
            for page in pdf.pages:
                page_text = page.extract_text(
                    x_tolerance=2,
                    y_tolerance=2,
                    layout=True,
                )
                if page_text:
                    text_plumber += page_text + "\n"
        results.append(("pdfplumber", text_plumber.strip()))
        logger.debug("pdfplumber extraction: %d chars", len(text_plumber.strip()))
    except Exception as e:
        logger.warning("pdfplumber extraction failed: %s", e)

    # ── Method 3: pypdf ──
    # Simple fallback for basic PDFs.
    try:
        from pypdf import PdfReader

        reader = PdfReader(io.BytesIO(pdf_bytes))
        text_pypdf = ""
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text_pypdf += page_text + "\n"
        results.append(("pypdf", text_pypdf.strip()))
        logger.debug("pypdf extraction: %d chars", len(text_pypdf.strip()))
    except Exception as e:
        logger.warning("pypdf extraction failed: %s", e)

    if not results:
        raise ValueError(
            "Nenhum método conseguiu extrair texto do PDF. "
            "O documento pode ser baseado em imagem (scaneado) "
            "— tente OCR via Tesseract."
        )

    # Return the longest result (presumed most complete)
    best_method, best_text = max(results, key=lambda x: len(x[1]))
    logger.info(
        "Best PDF extraction: method=%s chars=%d (total methods tried=%d)",
        best_method,
        len(best_text),
        len(results),
    )

    # Diagnostic: log the first 500 chars so operators can verify quality
    preview = best_text[:500].replace("\n", "\\n")
    logger.debug("TEXTO EXTRAÍDO (primeiros 500 chars): %s", preview)

    return best_text


def is_text_extraction_viable(pdf_bytes: bytes) -> bool:
    """Quick check: can we extract meaningful text from this PDF?

    If PyMuPDF returns fewer than 20 chars, this is likely an image-based
    PDF that needs OCR (Tesseract) instead of text extraction.

    Returns True if text extraction is viable, False if OCR is needed.
    """
    try:
        text = extract_pdf_text_robust(pdf_bytes)
        # Count actual word characters (letters/digits)
        word_chars = sum(1 for c in text if c.isalnum())
        return word_chars >= 20
    except Exception:
        return False
