# ============================================================
# PaySentinelIQ — Centralized Robust PDF Text Extractor
# ============================================================
# MÓDULO 0-A (Fundação Compartilhada):
#   Função ÚNICA para extração de PDF usada por TODOS os agentes
#   (boleto, contracheque, batch). 3 métodos em cascata com
#   métricas de qualidade e logging de diagnóstico.
#
#   NUNCA use pdfplumber/PdfReader diretamente no codebase.
#   SEMPRE chame extract_text_robust().
# ============================================================

from __future__ import annotations

import io
import logging
from typing import Any

logger = logging.getLogger("psi.extractor")


def extract_text_robust(pdf_bytes: bytes, document_type: str = "UNKNOWN") -> dict[str, Any]:
    """Extract text from a PDF using 3 methods in quality-priority cascade.

    Returns the most complete result plus quality diagnostics. This is the
    SINGLE centralized extraction function used by all agents (boleto,
    contracheque, batch). Never call pdfplumber/PdfReader directly.

    Method priority:
        1. PyMuPDF (fitz) — best for canvas/ReportLab/scanned PDFs
        2. pdfplumber       — excellent for tables & structured layouts
        3. pypdf            — universal fallback

    Args:
        pdf_bytes: Raw PDF file bytes.
        document_type: Label for logging (e.g. "BOLETO", "CONTRACHEQUE", "BATCH").

    Returns:
        dict with keys:
            - text: Best extracted text string
            - method: Which method produced the best result
            - char_count: Total characters extracted
            - extraction_quality: "GOOD" | "POOR" | "EMPTY"
            - all_attempts: List of all method results for diagnostics
            - word_chars: Count of alphanumeric characters (viability check)

    Raises:
        ValueError: If no method could extract any text.
    """
    attempts: list[dict[str, Any]] = []

    # ── Method 1: PyMuPDF (fitz) ──
    # Best for PDFs generated by ReportLab, iText, FPDF, and other
    # canvas-based generators. Uses TEXT_PRESERVE_WHITESPACE flag for
    # faithful layout preservation.
    try:
        import fitz  # PyMuPDF

        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        pages_text: list[str] = []
        for page in doc:
            blocks = page.get_text(
                "dict", flags=fitz.TEXT_PRESERVE_WHITESPACE
            )["blocks"]
            page_content: list[str] = []
            for block in blocks:
                if block.get("type") == 0:  # text block
                    for line in block.get("lines", []):
                        line_text = " ".join(
                            span["text"] for span in line.get("spans", [])
                        )
                        page_content.append(line_text)
            pages_text.append("\n".join(page_content))
        full_text = "\n\n".join(pages_text)
        doc.close()
        attempts.append({
            "method": "pymupdf",
            "text": full_text.strip(),
            "char_count": len(full_text.strip()),
            "pages": len(doc),
        })
    except Exception as e:
        logger.warning("[%s] PyMuPDF failed: %s", document_type, e)

    # ── Method 2: pdfplumber ──
    # Excellent for PDFs with table structures and conventional layouts.
    try:
        import pdfplumber

        with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
            pages_text = []
            for page in pdf.pages:
                text = page.extract_text(
                    x_tolerance=2, y_tolerance=2, layout=True
                ) or ""
                pages_text.append(text)
            full_text = "\n\n".join(pages_text)
        attempts.append({
            "method": "pdfplumber",
            "text": full_text.strip(),
            "char_count": len(full_text.strip()),
            "pages": len(pdf.pages),
        })
    except Exception as e:
        logger.warning("[%s] pdfplumber failed: %s", document_type, e)

    # ── Method 3: pypdf ──
    # Universal fallback for basic PDFs.
    try:
        from pypdf import PdfReader

        reader = PdfReader(io.BytesIO(pdf_bytes))
        full_text = ""
        for page in reader.pages:
            full_text += (page.extract_text() or "") + "\n"
        attempts.append({
            "method": "pypdf",
            "text": full_text.strip(),
            "char_count": len(full_text.strip()),
            "pages": len(reader.pages),
        })
    except Exception as e:
        logger.warning("[%s] pypdf failed: %s", document_type, e)

    if not attempts:
        raise ValueError(
            f"Nenhum método extraiu texto do PDF ({document_type}). "
            "O documento pode ser baseado em imagem (scaneado) "
            "ou estar protegido/corrompido."
        )

    # ── Select best result (longest = most complete) ──
    attempts.sort(key=lambda x: x["char_count"], reverse=True)
    best = attempts[0]

    # ── Quality assessment ──
    word_chars = sum(1 for c in best["text"] if c.isalnum())
    if best["char_count"] > 200:
        quality = "GOOD"
    elif best["char_count"] > 50:
        quality = "POOR"
    else:
        quality = "EMPTY"

    # ── Diagnostic logging ──
    method_summary = " | ".join(
        f"{a['method']}={a['char_count']}ch" for a in attempts
    )
    logger.info(
        "[%s] Extração: melhor=%s chars=%d qualidade=%s | %s",
        document_type,
        best["method"],
        best["char_count"],
        quality,
        method_summary,
    )

    if quality != "GOOD":
        logger.error(
            "[%s] EXTRAÇÃO %s: apenas %d chars (%d word chars). "
            "Resultado da análise pode ser impreciso. "
            "Considere OCR baseado em imagem (Tesseract).",
            document_type,
            quality,
            best["char_count"],
            word_chars,
        )

    # Preview for manual verification
    preview = best["text"][:500].replace("\n", "\\n")
    logger.debug("[%s] TEXTO EXTRAÍDO (500 chars): %s", document_type, preview)

    return {
        "text": best["text"],
        "method": best["method"],
        "char_count": best["char_count"],
        "word_chars": word_chars,
        "extraction_quality": quality,
        "all_attempts": attempts,
    }


def extract_pdf_text_robust(pdf_bytes: bytes) -> str:
    """Backward-compatible wrapper. Returns only the text string.

    Prefer extract_text_robust() for new code — it provides quality
    diagnostics that help detect extraction failures before they
    become false negatives.
    """
    result = extract_text_robust(pdf_bytes, document_type="LEGACY")
    return result["text"]


def is_text_extraction_viable(pdf_bytes: bytes) -> bool:
    """Quick check: can we extract meaningful text from this PDF?

    Returns True if text extraction yields >= 20 word characters,
    meaning the PDF has embedded text (not just scanned images).

    For scanned/image-based PDFs, this returns False — use Tesseract OCR.
    """
    try:
        result = extract_text_robust(pdf_bytes, document_type="VIABILITY_CHECK")
        return result["word_chars"] >= 20
    except Exception:
        return False
